name = "outdoors-telemetry"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "outdoors-telemetry"
database_id = "709c543f-f20f-453d-8976-322df615c2ac"
