name = "outdoors-referral"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "7faa6642d2b9b81acdbb6b12981d77d3"

[vars]
ADMIN_SECRET = "chiefton-admin-2026"

[[kv_namespaces]]
binding = "KV"
id = "2ad55b808de14dc892417d31c3555478"
